### ISSUE TITLE
Parametre ismi değişmiş

### ISSUE THREAD

**Issue by enderahmetyurt** [enderahmetyurt/veterinary-list-api#10]
@peyloride ```name``` parametresi neden ```name_like``` oldu? API name'de çalısmıyor şu an

**Comment by enderahmetyurt** [comment]
"You tried to define a scope named "name" on the model "Veterinary", but Active Record already defined a class method with the same name." bu hatayı almıssın sanırım ama keşke readme ye yazsaydık.

**Comment by peyloride** [comment]
@enderahmetyurt Scope olarak name set edilemiyor reserved key olduğu için. O yüzden değiştirmek zorunda kaldım.
