### ISSUE TITLE
Birden fazla parametre ile aynı anda arama yapılamıyor

### ISSUE THREAD

**Issue by peyloride** [enderahmetyurt/veterinary-list-api#6]
Search endpoint'te aynı anda birden fazla parametre ile arama yapılamıyor.

Örnek olarak;
`http://veterinaries.enderahmetyurt.com/search?city=ordu` Bize Ordu'daki veteriner listesini verirken,
`http://veterinaries.enderahmetyurt.com/search?name=ade&city=ordu` Bize Ordu'daki isminin içinde 'ade' geçen veterinerleri değil, tüm listede isminde 'ade' geçen veterinerleri veriyor.

Sorunun sebebi de gördüğüm kadarıyla parametreleri handle ederken kullanılan if-else yapısı. İlk parametreyi gördükten sonra ikincisine bakmıyor.

**Comment by enderahmetyurt** [comment]
@peyloride evet zaten öyle bir alt yapı yok. senden bekliyoruz ;)

**Comment by enderahmetyurt** [comment]
Close #7
