### ISSUE TITLE
Bir ile ait tüm veterinerlerin listesi

### ISSUE THREAD

**Issue by okandavut** [enderahmetyurt/veterinary-list-api#8]
Selamlar,
Öncelikle api çok kullanışlı elinize sağlık.

Bir ile ait listelidiğimde şu url ile sınırlı sayıda veteriner geliyor : http://veterinaries.enderahmetyurt.com/search?city=izmir

Ancak şu şekillerde aradığımda her sayfada farklı veterinerler geliyor : 
http://veterinaries.enderahmetyurt.com/search?city=izmir&page=1
http://veterinaries.enderahmetyurt.com/search?city=izmir&page=2
http://veterinaries.enderahmetyurt.com/search?city=izmir&page=3

Tüm veteriner listesinin tek json olarak geldiği yani atıyorum Izmir' e ait tüm veterinerleri listeyen url eklemesi yapılabilir. Ya da ben gözümden kaçırdım 😄 
Ben bu url ' in   ( http://veterinaries.enderahmetyurt.com/search?city=izmir ) tüm izmirdeki veterinerleri döndüreceğini düşünmüştüm.

Teşekkürler,
Saygılarımla.

**Comment by peyloride** [comment]
@okandavut Öneri için teşekkürler, bahsettiğin şekilde düzenledim. @enderahmetyurt PR'ı inceleyebilir misin?

**Comment by enderahmetyurt** [comment]
Eline sağlık @peyloride  Şimdi deploy edemiyorum @okandavut edince haber ederim.
